using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AgberoApp
{

   
    public class Ticket
    {
        //property of agbero ticket
        public int MonthlyTicket = 100;
        public int DailyTicket = 50;
        public int TicketSold { get; set; }
        public double Balance { get; set; }



        //fixed price
        public Ticket()
        {
            Balance = 0;
            TicketSold = 0;

        }

        // 10 digits random number generated by default
        public string RandomTicketID(int length)
        {
            var random = new Random();
            string s = string.Empty;
            for (int i = 0; i < length; i++)
            {
                s = String.Concat(s, random.Next(10).ToString());
            }
            return s;
        }
        //methods
        public void Operation()
        {
            Console.WriteLine("\n OGA NLA ");
            Console.WriteLine("Kilofese. \n1. Buy Ticket \n2.To Get Detail");
            int userInput = int.Parse(Console.ReadLine());

            while (userInput == 1)
            {
                BuyTicket();
                Console.WriteLine("Kilofese. \n1. Buy Ticket \n2.To Get Detail");
                userInput = int.Parse(Console.ReadLine());

                TicketSold++;
            }
            Summation();
        }

        public void BuyTicket()
        {

            double price;
            Console.WriteLine("Choose a ticket type: \n1. Daily \n2. Monthly");

            int userInput = int.Parse(Console.ReadLine());


            if (userInput == 1)
            {
                price = MonthlyTicket;
            }
            else
            {
                price = DailyTicket;
            }
            Balance += price;
            Console.WriteLine($"Ticket Generated! Ticket Id is:  { RandomTicketID(10)}");
        }

        //acitivity summary
        public void Summation()
        {
            double owochairman = 0.65 * Balance;
            Console.WriteLine($"Today Tickect {TicketSold}");
            Console.WriteLine($"Month Ticket {Balance}");
            Console.WriteLine($"Owo Chairman #{owochairman}");
        }
    }
}
